"""Zowe Client Python SDK.

This program and the accompanying materials are made available under the terms of the
Eclipse Public License v2.0 which accompanies this distribution, and is available at

https://www.eclipse.org/legal/epl-v20.html

SPDX-License-Identifier: EPL-2.0

Copyright Contributors to the Zowe Project.
"""

from typing import Optional, Any, Union

from requests import Response

from zowe.core_for_zowe_sdk import SdkApi
from zowe.zos_files_for_zowe_sdk.constants import FileType, zos_file_constants
from zowe.zos_files_for_zowe_sdk.response import DatasetListResponse, MemberListResponse
from zowe.zos_files_for_zowe_sdk.response.file_system import FileSystemListResponse


from .datasets import DatasetOption, Datasets
from .file_system import FileSystems
from .uss import USSFiles

_ZOWE_FILES_DEFAULT_ENCODING = zos_file_constants["ZoweFilesDefaultEncoding"]


class Files(SdkApi):  # type: ignore
    """
    Class used to represent the base z/OSMF Files API.

    Attributes
    ----------
    ds: Datasets
        A Datasets class object
    uss: USSFiles
        An USSFiles class object
    fs: FileSystems
        A FileSystems class object

    Parameters
    ----------
    connection: dict[str, Any]
        The z/OSMF connection object (generated by the ZoweSDK object)
    log : bool
        Flag to disable logger
    """

    ds: Datasets
    uss: USSFiles
    fs: FileSystems

    def __init__(self, connection: dict[str, Any], log: bool = True):
        super().__init__(connection, "/zosmf/restfiles/", logger_name=__name__, log=log)
        self._default_headers["Accept-Encoding"] = "gzip"
        self.ds = Datasets(connection)
        self.uss = USSFiles(connection)
        self.fs = FileSystems(connection)

    def list_files(self, path: str) -> Any:
        """Use uss.list() instead of this deprecated function."""
        return self.uss.list(path)

    def get_file_content_streamed(self, file_path: str, binary: bool = False) -> Response:
        """Use uss.get_content_streamed() instead of this deprecated function."""
        return self.uss.get_content_streamed(file_path, binary)

    def get_file_content(self, filepath_name: str) -> Optional[str]:
        """Use uss.get_content() instead of this deprecated function."""
        return self.uss.get_content(filepath_name)

    def delete_uss(self, filepath_name: str, recursive: bool = False) -> None:
        """Use uss.delete() instead of this deprecated function."""
        return self.uss.delete(filepath_name, recursive)

    def list_dsn(self, name_pattern: str, return_attributes: bool = False) -> DatasetListResponse:
        """Use ds.list() instead of this deprecated function."""
        return self.ds.list(name_pattern, return_attributes)

    def list_dsn_members(
        self,
        dataset_name: str,
        member_pattern: Optional[str] = None,
        member_start: Optional[str] = None,
        limit: int = 1000,
        attributes: str = "member",
    ) -> MemberListResponse:
        """Use ds.list_members() instead of this deprecated function."""
        return self.ds.list_members(dataset_name, member_pattern, member_start, limit, attributes)

    def copy_uss_to_data_set(
        self,
        from_filename: str,
        to_dataset_name: str,
        to_member_name: Optional[str] = None,
        type: FileType = FileType.TEXT,
        replace: bool = False,
    ) -> None:
        """Use ds.copy_uss_to_data_set() instead of this deprecated function."""
        return self.ds.copy_uss_to_data_set(from_filename, to_dataset_name, to_member_name, type, replace)

    def copy_data_set_or_member(
        self,
        from_dataset_name: str,
        to_dataset_name: str,
        from_member_name: Optional[str] = None,
        volser: Optional[str] = None,
        alias: Optional[bool] = None,
        to_member_name: Optional[str] = None,
        enq: Optional[str] = None,
        replace: bool = False,
    ) -> None:
        """Use ds.copy_data_set_or_member() instead of this deprecated function."""
        return self.ds.copy_data_set_or_member(
            from_dataset_name, to_dataset_name, from_member_name, volser, alias, to_member_name, enq, replace
        )

    def get_dsn_content(self, dataset_name: str) -> Optional[str]:
        """Use ds.get_content() instead of this deprecated function."""
        return self.ds.get_content(dataset_name)

    def create_data_set(self, dataset_name: str, options: Optional[DatasetOption] = None) -> None:
        """Use ds.create() instead of this deprecated function."""
        return self.ds.create(dataset_name, options)

    def create_default_data_set(self, dataset_name: str, default_type: str) -> None:
        """Use ds.create_default() instead of this deprecated function."""
        return self.ds.create_default(dataset_name, default_type)

    def create_uss(self, file_path: str, file_type: str, mode: Optional[str] = None) -> None:
        """Use uss.create() instead of this deprecated function."""
        return self.uss.create(file_path, file_type, mode)

    def get_dsn_content_streamed(self, dataset_name: str) -> Response:
        """Use ds.get_content() instead of this deprecated function."""
        return self.ds.get_content(dataset_name, stream=True)

    def get_dsn_binary_content(self, dataset_name: str, with_prefixes: bool = False) -> bytes:
        """Use ds.get_binary_content() instead of this deprecated function."""
        return self.ds.get_binary_content(dataset_name, with_prefixes)

    def get_dsn_binary_content_streamed(self, dataset_name: str, with_prefixes: bool = False) -> Response:
        """Use ds.get_binary_content() instead of this deprecated function."""
        return self.ds.get_binary_content(dataset_name, stream=True, with_prefixes=with_prefixes)

    def write_to_dsn(
        self, dataset_name: str, data: Union[str, bytes], encoding: str = _ZOWE_FILES_DEFAULT_ENCODING
    ) -> None:
        """Use ds.write() instead of this deprecated function."""
        return self.ds.write(dataset_name, data, encoding)

    def download_dsn(self, dataset_name: str, output_file: str) -> None:
        """Use ds.download() instead of this deprecated function."""
        return self.ds.download(dataset_name, output_file)

    def download_binary_dsn(self, dataset_name: str, output_file: str, with_prefixes: bool = False) -> None:
        """Use ds.download_binary() instead of this deprecated function."""
        return self.ds.download_binary(dataset_name, output_file, with_prefixes)

    def upload_file_to_dsn(
        self, input_file: str, dataset_name: str, encoding: str = _ZOWE_FILES_DEFAULT_ENCODING, binary: bool = False
    ) -> None:
        """Use ds.upload_file() instead of this deprecated function."""
        return self.ds.upload_file(input_file, dataset_name, encoding, binary)

    def write_to_uss(self, filepath_name: str, data: str, encoding: str = _ZOWE_FILES_DEFAULT_ENCODING) -> None:
        """Use uss.write() instead of this deprecated function."""
        return self.uss.write(filepath_name, data, encoding)

    def upload_file_to_uss(
        self, input_file: str, filepath_name: str, encoding: str = _ZOWE_FILES_DEFAULT_ENCODING
    ) -> None:
        """Use uss.upload() instead of this deprecated function."""
        return self.uss.upload(input_file, filepath_name, encoding)

    def download_uss(self, file_path: str, output_file: str, binary: bool = False) -> None:
        """Use uss.download() instead of this deprecated function."""
        return self.uss.download(file_path, output_file, binary)

    def delete_data_set(
        self, dataset_name: str, volume: Optional[str] = None, member_name: Optional[str] = None
    ) -> None:
        """Use ds.delete() instead of this deprecated function."""
        return self.ds.delete(dataset_name, volume, member_name)

    def create_zfs_file_system(self, file_system_name: str, options: Optional[dict[str, Any]] = None) -> None:
        """Use fs.create() instead of this deprecated function."""
        options = options or {}
        return self.fs.create(file_system_name, options)

    def delete_zfs_file_system(self, file_system_name: str) -> None:
        """Use fs.delete() instead of this deprecated function."""
        return self.fs.delete(file_system_name)

    def mount_file_system(
        self,
        file_system_name: str,
        mount_point: str,
        options: dict[str, Any] = {},
        encoding: str = _ZOWE_FILES_DEFAULT_ENCODING,
    ) -> None:
        """Use fs.mount() instead of this deprecated function."""
        return self.fs.mount(file_system_name, mount_point, options, encoding)

    def unmount_file_system(
        self,
        file_system_name: str,
        options: Optional[dict[str, Any]] = None,
        encoding: str = _ZOWE_FILES_DEFAULT_ENCODING,
    ) -> None:
        """Use fs.unmount() instead of this deprecated function."""
        return self.fs.unmount(file_system_name, options or {}, encoding)

    def list_unix_file_systems(
        self, file_path_name: Optional[str] = None, file_system_name: Optional[str] = None
    ) -> FileSystemListResponse:
        """Use fs.list() instead of this deprecated function."""
        return self.fs.list(file_path_name, file_system_name)

    def recall_migrated_data_set(self, dataset_name: str, wait: bool = False) -> None:
        """Use ds.recall_migrated() instead of this deprecated function."""
        return self.ds.recall_migrated(dataset_name, wait)

    def delete_migrated_data_set(self, dataset_name: str, purge: bool = False, wait: bool = False) -> None:
        """Use ds.delete_migrated() instead of this deprecated function."""
        return self.ds.delete_migrated(dataset_name, purge, wait)

    def migrate_data_set(self, dataset_name: str, wait: bool = False) -> None:
        """Use ds.migrate() instead of this deprecated function."""
        return self.ds.migrate(dataset_name, wait)

    def rename_data_set(self, before_dataset_name: str, after_dataset_name: str) -> None:
        """Use ds.rename() instead of this deprecated function."""
        return self.ds.rename(before_dataset_name, after_dataset_name)

    def rename_data_set_member(
        self, dataset_name: str, before_member_name: str, after_member_name: str, enq: str = ""
    ) -> None:
        """Use ds.rename_member() instead of this deprecated function."""
        return self.ds.rename_member(dataset_name, before_member_name, after_member_name, enq)
