"""Zowe Python Client SDK.

This program and the accompanying materials are made available under the terms of the
Eclipse Public License v2.0 which accompanies this distribution, and is available at

https://www.eclipse.org/legal/epl-v20.html

SPDX-License-Identifier: EPL-2.0

Copyright Contributors to the Zowe project.
"""

from zowe.core_for_zowe_sdk import SdkApi


class Zosmf(SdkApi):
    """
    Class used to represent the base z/OSMF API.

    Attributes
    ----------
    connection
        Connection object
    """

    def __init__(self, connection):
        """
        Construct a Zosmf object.

        Parameters
        ----------
        connection
            The z/OSMF connection object (generated by the ZoweSDK object)
        """
        super().__init__(connection, "/zosmf/info", logger_name=__name__)

    def get_info(self):
        """Return a JSON response from the GET request to z/OSMF info endpoint.

        Returns
        -------
        json
            A JSON containing the z/OSMF Info REST API data
        """
        response_json = self.request_handler.perform_request("GET", self._request_arguments)
        return response_json

    def list_systems(self):
        """Return a JSON response from the GET request to z/OSMF info endpoint.
        Returns
        -------
        json
            Return a list of the systems that are defined to a z/OSMF instance
        """

        custom_args = self._create_custom_request_arguments()
        custom_args["url"] = "{}/systems".format(self._request_endpoint)
        response_json = self.request_handler.perform_request("GET", custom_args, expected_code=[200])
        return response_json
