[package]
name = "keyring"
readme = "README.md"
repository = "https://github.com/zowe/zowe-client-python-sdk"
version = "1.0.0-dev12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "keyring"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["abi3-py310", "generate-import-lib"] }
# Pinned to a commit so builds are reproducible
secrets_core = { git = "https://github.com/zowe/zowe-cli.git", rev = "fc8b31ce0de3c7c8a9a371dd43f3daf6a133f002" } # v8.35.2
